using System.ComponentModel.DataAnnotations;

namespace ManagementPages.Model.InformationBoard
{
    public class InformationBoardDataModel
    {
        public bool ContentIsValid => CheckIfContentIsValid();

        public int InformationBoardId { get; set; } //generated by database

        public int LicenseId { get; set; }

        [Required(ErrorMessage = "Titel-feltet skal udfyldes")]
        [StringLength(30, ErrorMessage = "Titlen er for lang")]
        public string Title { get; set; }

        public string Url { get; set; }

        public string QRCode { get; set; }

        public bool IsPublished { get; set; }

        public string CategoryOrder { get; set; }

        private bool CheckIfContentIsValid()
        {
            return !string.IsNullOrEmpty(Title) && Title.Length <= 30
                                                && InformationBoardId > 0
                                                && LicenseId > 0;
        }
    }
}