using System.ComponentModel.DataAnnotations;

namespace ManagementPages.Model.Category
{
    public class CategoryDataModel
    {
        public bool ContentIsValid => CheckIfContentIsValid();

        private bool CheckIfContentIsValid()
        {
            return !string.IsNullOrEmpty(Title) && Title.Length <= 30
                                                && CategoryId > 0
                                                && InformationBoardId > 0
                                                && !string.IsNullOrEmpty(Icon);
        }

        public int CategoryId { get; set; } //generated by database

        public int InformationBoardId { get; set; }

        [Required(ErrorMessage = "Titel-feltet skal udfyldes")]
        [StringLength(30, ErrorMessage = "Titlen er for lang")]
        public string Title { get; set; }

        public bool IsPublished { get; set; }

        [Required(ErrorMessage = "Vælg et ikon")]
        [StringLength(30, ErrorMessage = "Det valgte ikon kan ikke bruges. Vælg et andet")]
        public string Icon { get; set; }
    }
}