using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;

namespace ManagementPages.Model
{
    public class License
    {
        public int LicenseId { get; set; } //generated by database

        public DateTime RegistrationDate { get; set; }
    }
}
