using System;

namespace ManagementPages.Model
{
    public class LicenseModel
    {
        public int LicenseId { get; set; } //generated by database

        public string CustomerName { get; set; }

        public DateTime RegistrationDate { get; set; }
    }
}